title: Blog Bibliotheks- und Archivinformatik
author: Felix
email: felix.lohmeier@fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  Blog für den Kurs Bibliotheks- und Archinformatik FS2020

# social links
twitter_username: felixlohmeier # DO NOT include the @ character, or else the build will fail!
github_username:  felixlohmeier # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
